MovieRental/Areas/Admin/Controllers/BulkLoadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using MovieRental.Models;
using MovieRental.BL;
using MovieRental.Areas.Admin.Models;
using MovieRental.Data;

namespace MovieRental.Areas.Admin.Controllers
{
    public class BulkLoadController : Controller
    {
        // GET: Admin/BulkLoad
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string movieList, double defaultRentalrate, int defaultQty)
        {
            string[] titles = titles = Regex.Split(movieList, "\r\n|\r|\n");

            List<string> unresolvedTitles = new List<string>();
            List<Movie> resolvedMovie = new List<Movie>();

            foreach(string title in titles)
            {
                Movie m = OMDBService.GetMovieByTitle(title);
                if (m != null)
                {
                    m.RentalRate = defaultRentalrate;
                    m.NoInStock = defaultQty;
                    resolvedMovie.Add(m);
                }
                else
                {
                    if (!string.IsNullOrEmpty(title))
                    {
                        unresolvedTitles.Add(title);
                    }
                }
            }

            BulkLoadOutput blo = new BulkLoadOutput(unresolvedTitles, resolvedMovie);

            TempData["blo"] = blo;
            return View("BulkOutput", blo);
        }

        [HttpPost]

        public ActionResult Save(String save)
        {
            List<String> messages = new List<string>();

            if (save == "Yes")
            {
                BulkLoadOutput blo = (BulkLoadOutput) TempData["blo"];
                List<Movie> movies = blo == null?
                    new List<Movie>():blo.ResolvedMovie;
                MovieRepository rep = new MovieRepository();

                foreach (Movie m in movies)
                {
                    try
                    {
                        rep.Add(m);
                        rep.Save();
                        messages.Add("Successfully add movie " + m.Title);
                    }
                    catch
                    {
                        messages.Add("Unable to add movie " + m.Title + ". Perhaps it is already in database.");
                    }
                }
            }
            else
            {
                messages.Add("Bulk Load operation is successfully cancelled.");
            }

            return View(messages);
        }
    }
}

MovieRental/Areas/Admin/Views/BulkLoad/BulkOutput.cshtml
@model MovieRental.Areas.Admin.Models.BulkLoadOutput
@using MovieRental.Models

@{
    ViewBag.Title = "BulkOutput";
}

<h2>Information Retrieved From Open Movie Database</h2>

@if (Model.UnresolveTitles.Count > 0)
{
    <h3>Unable to find a match for the following:</h3>
    foreach (String item in Model.UnresolveTitles)
    {
        <li>@item</li>
    }
}

<div>
    <h3>Match Found For The Following Movies</h3>
    @foreach (var m in Model.ResolvedMovie)
    {
        <div style="width: 320px; height:520px;float:left">
            @Html.DisplayFor(modelItem => m)
        </div>
    }
</div>

<div style="float:left">
    <p>
        Do You want to add all these movie?
    </p>
    <p>
        @using(Html.BeginForm("Save", "BulkLoad"))
        {
            <input style="color:green, font-weight:bold" type="submit" name="Save" value="Yes" />
            <input style="color:red, font-weight:bold" type="submit" name="Save" value="No" />
        }
    </p>
</div>

MovieRental/Areas/Admin/Views/BulkLoad/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Movie Bulk Loader</h2>
Enter List of Movies (one line per movies) to load
@using (Html.BeginForm()) 
{
    @Html.TextArea("MovieList")
    <p>Default Rental Rate:<br />@Html.TextBox("defaultRentalRate")</p>
    <p>Default Quantity:<br/>@Html.TextBox("defaultQty")</p>
    <p><input type ="submit" value = "Submit"</p>
}

MovieRental/Areas/Admin/Views/BulkLoad/Save.cshtml
@model List<String>
         
@{
    ViewBag.Title = "Bulk Load Result";
}

<h2>Bulk Load Result</h2>
@foreach (String message in Model)
{
    <p>
        @message
    </p>
}